news/urls.py
from django.urls import path

from .views import PostList, PostDetail, PostFil, PostCreateNE, PostUpdate, PostDelete, MyPosts, set_timezone


urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('search/', PostFil.as_view(), name='post_filter'),
    path('create/', PostCreateNE.as_view(), name='post_create_ne'),
    path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update_ne'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete_ne'),
    path('myposts/', MyPosts.as_view(), name='my_posts'),
    path('set_timezone/', set_timezone, name='set_timezone'),
]

newsportal/urls.py
from django.contrib import admin
from django.urls import path, include

from news.views import subscriptions

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('articles/', include('news.ar_urls')),
    path('accounts/', include('allauth.urls')),
    path('subscriptions/', subscriptions, name='subscriptions'),
]

news/models.py
from django.core.cache import cache
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Coalesce


class Author(models.Model):
    rating_author = models.IntegerField(default=0)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def update_rating(self):
        post_rate = Post.objects.filter(author=self).aggregate(pr=Coalesce(Sum('rating_post'), 0))['pr']
        com_rate = Comment.objects.filter(user=self.user).aggregate(cr=Coalesce(Sum('rating_comm'), 0))['cr']
        post_com_rate = Comment.objects.filter(post__author=self).aggregate(pcr=Coalesce(Sum('rating_comm'), 0))['pcr']

        self.rating_author = (post_rate * 3) + com_rate + post_com_rate
        self.save()


class Category(models.Model):
    cat_name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.cat_name


class Post(models.Model):

    news = 'NE'
    article = 'AR'

    N_A = [
        (news, 'Новости'),
        (article, 'Статья')
    ]

    news_article = models.CharField(max_length=2,
                                    choices=N_A,
                                    default=news)
    time_in = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating_post = models.IntegerField(default=0)

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, through='PostCategory')

    def like(self):
        self.rating_post += 1
        self.save()

    def dislike(self):
        self.rating_post -= 1
        self.save()

    def preview(self):
        if len(self.text) > 124:
            return self.text[:124] + '...'
        return self.text

    def get_absolute_url(self):
        return f'/news/{self.id}'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    text_comm = models.TextField()
    time_comm = models.DateTimeField(auto_now_add=True)
    rating_comm = models.IntegerField(default=0)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def like(self):
        self.rating_comm += 1
        self.save()

    def dislike(self):
        self.rating_comm -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

templates/my_posts.html
{% extends 'flatpages/default.html' %}

{% load i18n %}
{% load custom_filters %}

{% block title %}
{% trans "Мои посты" %}
{% endblock title %}

{% block content %}
    <h1>{% trans "Мои посты" %}</h1>
    <hr>
    {% if posts %}
       <table>
           <tr>
               <td>{% trans "Название" %}</td>
               <td></td>
               <td>{% trans "Дата публикации" %}</td>
               <td></td>
               <td>{% trans "Превью" %}</td>
               <td></td>
               <td>{% trans "Действия"%}</td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.title }}</td>
               <td></td>
               <td>{{ post.time_in|date:'M d Y' }}</td>
               <td></td>
               <td>{{ post.text|truncatewords:20 }}</td>
               <td></td>
               <td><a href="http://127.0.0.1:8000/news/{{ post.id }}">{% trans "Просмотреть" %}</a> </td>
               <td></td>
               {% if perms.news.change_post and post.author.user_id == user.id %}
               <td><a href="http://127.0.0.1:8000/news/{{ post.id }}/edit">{% trans "Изменить" %}</a></td>
               {% endif %}
               <td></td>
               {% if post.author.user_id == user.id %}
               <td><a href="http://127.0.0.1:8000/news/{{ post.id }}/delete">{% trans "Удалить" %}</a></td>
               {% endif %}
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>{% trans "Нет постов" %}</h2>
   {% endif %}
{% endblock content %}

templates/post.html
{% extends 'flatpages/default.html' %}

{% load i18n %}
{% load custom_filters %}

{% block title %}
{{post.title}}
{% endblock title %}

{% block content %}
    <h1>{% trans "Название:" %} {{ post.title }}</h1>
    <h6>{{ post.get_news_article_display }}</h6>
    <h2>{% trans "Дата публикации:" %} {{ post.time_in|date:'M d Y' }}</h2>
    <h3>{% trans "Автор:" %} {{ post.author }}</h3>
    <h5>{% trans "Рейтинг поста:" %} {{ post.rating_post }}</h5>
    <h4>{% trans "Категории:" %}</h4>
    <ul>
        {% for category in post.category.all %}
            <li>{{ category.cat_name }}</li>
        {% empty %}
            <li>{% trans "Нет категорий" %}</li>
        {% endfor %}
    </ul>

    <hr>
    <h3>{{ post.text }}</h3>
{% endblock content %}

templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block content %}
<h1>{% trans "Удалить пост" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans "Удалить" %} "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block content %}
<h1>{% trans "Добавить изменения" %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/post_search.html
{% extends 'flatpages/default.html' %}

{% load i18n %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
{% trans "Посты" %}
{% endblock title %}

{% block content %}
   <h1>{% trans "Найти пост" %}</h1>
   <h3>{% trans "Постов на странице:" %} {{ posts|length }}</h3>
   <hr>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>


   {% if posts %}
       <table>
           <tr>
               <td>{% trans "Название" %}</td>
               <td>{% trans "Дата публикации" %}</td>
               <td>{% trans "Превью" %}</td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.title }}</td>
               <td>{{ post.time_in|date:'M d Y' }}</td>
               <td>{{ post.text|truncatewords:20 }}</td>
               <td><a href="http://127.0.0.1:8000/news/{{ post.id }}">{% trans "Просмотреть" %}</a> </td>
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>{% trans "Нет постов с такими параметрами!" %}</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/posts.html
{% extends 'flatpages/default.html' %}

{% load i18n %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
{% trans "Посты" %}
{% endblock title %}

{% block content %}
   <h1>{% trans "Все посты" %}</h1>
   <a href="http://127.0.0.1:8000/news/search">{% trans "Найти пост" %}</a>
   <h3>{% trans "Постов на странице:" %} {{ posts|length }}</h3>
   <hr>
   {% if perms.news.add_post %}
   <a href="http://127.0.0.1:8000/news/create/">{% trans "Добавить новость" %}</a>
   <br>
   <a href="http://127.0.0.1:8000/articles/create/">{% trans "Добавить статью" %}</a>
   <hr>
   {% endif %}
   {% if posts %}
       <table>
           <tr>
               <td>{% trans "Название" %}</td>
               <td></td>
               <td>{% trans "Дата публикации" %}</td>
               <td></td>
               <td>{% trans "Превью" %}</td>
               <td></td>
               <td>{% trans "Автор" %}</td>
               <td></td>
               <td>{% trans "Действия" %}</td>
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.title }}</td>
               <td></td>
               <td>{{ post.time_in|date:'M j, Y H:i' }}</td>
               <td></td>
               <td>{{ post.text|truncatewords:20 }}</td>
               <td></td>
               <td>{{ post.author }}</td>
               <td></td>
               <td><a href="http://127.0.0.1:8000/news/{{ post.id }}">{% trans "Просмотреть" %}</a> </td>
               <td></td>
               {% if user.is_superuser %}
               <td><a href="http://127.0.0.1:8000/news/{{ post.id }}/edit">{% trans "Изменить" %}</a></td>
               {% endif %}
               <td></td>
               {% if perms.news.delete_post and post.author.user_id == user.id or user.is_superuser %}
               <td><a href="http://127.0.0.1:8000/news/{{ post.id }}/delete">{% trans "Удалить" %}</a></td>
               {% endif %}
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>{% trans "Нет постов!" %}</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% load i18n %}

{% block title %}
{% trans "Подписки" %}
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.cat_name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>{% trans "Подписаться" %}</button>
                    <button name="action" value="unsubscribe">{% trans "Отписаться" %}</button>
                {% else %}
                    <button name="action" value="subscribe">{% trans "Подписаться" %}</button>
                    <button disabled>{% trans "Отписаться" %}</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}